services:
  node:
    build: ./node
    ports:
      - 3001:3001
      - 8080:8080
    environment:
      # Application Configuration
      SERVER_PORT: ${SERVER_PORT}
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./node/src:/server/src/src
      - ./node/server.js:/server/src/server.js
    deploy:
      resources:
        limits:
          memory: 4GB
        reservations:
          memory: 2GB

