name: app_ui
description: "Main UI package CV Client App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <5.0.0'

dependencies:
  animations: ^2.0.11
  api_client:
    path: ../api_client
  app_core:
    path: ../app_core
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.70.2
  google_fonts: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^6.0.0

flutter:
  generate: true
