// File: lib/core/cache/cached_http_response.dart
import 'package:isar/isar.dart';

part 'cached_http_response.g.dart'; // This file will be generated by Isar

@Collection()
class CachedHttpResponse {
  Id id = Isar.autoIncrement;

  @Index(unique: true, replace: true)
  late String key;

  late String data;

  late DateTime cachedAt;

  DateTime? expiresAt;

  CachedHttpResponse({
    required this.key,
    required this.data,
    required this.cachedAt,
    this.expiresAt,
  });

  factory CachedHttpResponse.fromResponse({
    required String key,
    required String responseBody,
    Duration? cacheDuration,
  }) {
    final now = DateTime.now().toUtc();
    return CachedHttpResponse(
      key: key,
      data: responseBody,
      cachedAt: now,
      expiresAt: cacheDuration != null ? now.add(cacheDuration) : null,
    );
  }
}
