name: api_client
description: "Main package the app's APIs"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  dio: ^5.8.0+1
  jwt_decoder: ^2.0.1
  isar:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  isar_flutter_libs:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8
  get_it: ^8.0.3 

dev_dependencies:
  very_good_analysis: ^6.0.0

  build_runner: ^2.4.7
  isar_generator:
    hosted: https://pub.isar-community.dev
    version: ^3.1.8

flutter:
  generate: true
